guardar_formula:
  name: Guardar Fórmula
  description: Guarda de forma asíncrona la receta actual con todos sus porcentajes e ingredientes en el almacenamiento seguro de Home Assistant (Store).

confirmar_sobreescritura:
  name: Confirmar Sobreescritura
  description: Sobreescribe y actualiza de forma segura la receta activa en el Store tras la confirmación de la interfaz.

confirmar_eliminacion:
  name: Confirmar Eliminación
  description: Destruye y purga de forma definitiva del Store la receta activa actualmente en el obrador.

cargar_formula_en_sliders:
  name: Cargar Fórmula en Sliders
  description: Carga una receta guardada en el Store y mueve de forma asíncrona todos los sliders numéricos e ingredientes en Lovelace.
  fields:
    nombre:
      name: Nombre de la receta
      description: Identificador de la fórmula que se desea cargar en el obrador.
      required: true
      example: pizza_napolitana

balancear_harinas:
  name: Balancear Harinas
  description: Motor matemático reactivo que calcula las harinas netas y líquidos en directo descontando los porcentajes de prefermentos.
  fields:
    harina_origen:
      name: Harina Origen
      description: ID de la harina que ha cambiado para forzar el balanceo del 100%.
      required: false
      example: 1

anadir_harina:
  name: Añadir Harina al Almacén
  description: Registra una nueva marca o variedad de harina de forma permanente en el Store de harinas de la integración.

eliminar_harina:
  name: Eliminar Harina del Almacén
  description: Purga del Store de harinas del inventario del obrador la variedad de harina seleccionada en el menú de retirada.
